delivery/urls.py
from django.urls import path

from delivery.views import (
    index,
    about,
    PizzaMenuListView,
    CustomerDetailView,
    CustomerUpdateView,
    ToppingListView,
    ToppingUpdateView,
    ToppingCreateView,
    ToppingDeleteView,
    RegisterView,
    PizzaUpdateView,
    PizzaCreateView,
    PizzaDeleteView,
    OrderListView,
    OrderAddPizzaView,
    OrderDeleteView,
    IncrementQuantityView,
    DecrementQuantityView,
    FeedBackListView,
    create_receipt,
    ReceiptListView,
    clean_order,
    ChooseToppingView,
)

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("menu/", PizzaMenuListView.as_view(), name="pizza-menu-list"),
    path(
        "menu/type/<int:type_id>/",
        PizzaMenuListView.as_view(),
        name="pizza-menu-type-list",
    ),
    path(
        "menu/pizza/<int:pk>/update/",
        PizzaUpdateView.as_view(),
        name="pizza-update"
    ),
    path(
        "menu/create/",
        PizzaCreateView.as_view(),
        name="pizza-create"
    ),
    path(
        "menu/<int:pk>/delete/",
        PizzaDeleteView.as_view(),
        name="pizza-delete"
    ),
    path(
        "customer/<int:pk>/",
        CustomerDetailView.as_view(),
        name="customer-detail"
    ),
    path(
        "customer/<int:pk>/update/",
        CustomerUpdateView.as_view(),
        name="customer-update",
    ),
    path(
        "registration/",
        RegisterView.as_view(),
        name="customer-register"
    ),
    path(
        "topping/<int:pk>/update",
        ToppingUpdateView.as_view(),
        name="topping-update"
    ),
    path(
        "topping/create/",
        ToppingCreateView.as_view(),
        name="topping-create"
    ),
    path(
        "topping/<int:pk>/delete/",
        ToppingDeleteView.as_view(),
        name="topping-delete"
    ),
    path(
        "topping/",
        ToppingListView.as_view(),
        name="topping-list"
    ),
    path(
        "order/",
        OrderListView.as_view(),
        name="order-list"
    ),
    path(
        "order/add-pizza/<int:pizza_id>/",
        OrderAddPizzaView.as_view(),
        name="order-add-pizza",
    ),

    path(
        "order-delete/<int:order_id>/<int:pizza_id>/",
        OrderDeleteView.as_view(),
        name="order-delete",
    ),
    path(
        "increment/<int:pk>/",
        IncrementQuantityView.as_view(),
        name="order-increment"
    ),
    path(
        "decrement/<int:pk>/",
        DecrementQuantityView.as_view(),
        name="order-decrement"
    ),
    path("feedback/", FeedBackListView.as_view(), name="feedback-list"),
    path("create-receipt/", create_receipt, name="receipt-create"),
    path("receipt/", ReceiptListView.as_view(), name="receipt-list"),
    path("clean-order/<int:pk>/", clean_order, name="clean-order"),
    path(
        "order/<int:pk>/add_toppings/",
        ChooseToppingView.as_view(),
        name="choose-topping"
    ),
]

app_name = "delivery"

delivery_pizza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("delivery.urls", namespace="delivery")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

delivery/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from delivery_pizza import settings


class Customer(AbstractUser):
    address = models.CharField(max_length=255, blank=False, null=False)
    phone_number = models.CharField(max_length=255, blank=False, null=False)

    class Meta:
        verbose_name = "customer"
        ordering = ["username"]

    def get_absolute_url(self) -> str:
        return reverse("delivery:customer-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return (
            f"{self.first_name} "
            f"{self.last_name} "
            f"{self.email} "
            f"{self.address} "
            f"{self.phone_number}"
        )


class FeedBack(models.Model):
    comment = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="feedback",
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ["created_time"]


class PizzaType(models.Model):
    type = models.CharField(max_length=63)

    def __str__(self) -> str:
        return f"{self.type}"


class Topping(models.Model):
    name = models.CharField(max_length=63)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        ordering = ["price"]

    def __str__(self) -> str:
        return f"{self.name}: {self.price}"


class Pizza(models.Model):
    name = models.CharField(max_length=63)
    type_pizza = models.ForeignKey(PizzaType, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    price_with_toppings = models.DecimalField(
        max_digits=6, decimal_places=2, default=0
    )
    ingredients = models.TextField(blank=True, null=True)
    topping = models.ManyToManyField(
        Topping, related_name="pizza_topping"
    )
    quantity = models.IntegerField(default=1)
    is_custom_pizza = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return f"{self.name}: {self.price}"


class Order(models.Model):
    pizza = models.ManyToManyField(Pizza, related_name="order")
    status = models.BooleanField(default=False)
    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return f"{self.pizza.name}"


class Receipt(models.Model):
    customer_order = models.ForeignKey(Order, on_delete=models.CASCADE)
    order_time = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Receipt #{self.pk} ({self.order_time})"

delivery/views.py
from abc import abstractmethod

from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from django.db.models import QuerySet

from delivery.forms import (
    CustomerInfoUpdateForm,
    RegisterForm,
    ToppingSearchForm,
    FeedBackCreateForm,
    PizzaForm,
)
from delivery.models import (
    Pizza,
    Topping,
    FeedBack,
    PizzaType,
    Customer,
    Order,
    Receipt,
)


def index(request) -> HttpResponse:
    pizza_count = Pizza.objects.count()
    topping_count = Topping.objects.count()
    feedback_count = FeedBack.objects.count()
    pizza_type_count = PizzaType.objects.count()

    context = {
        "pizza_count": pizza_count,
        "topping_count": topping_count,
        "feedback_count": feedback_count,
        "pizza_type_count": pizza_type_count,
    }

    return render(request, "delivery/home.html", context=context)


def about(request) -> HttpResponse:
    return render(request, "delivery/about_delivery.html")


class CustomerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Customer
    queryset = Customer.objects.all()


class CustomerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Customer
    form_class = CustomerInfoUpdateForm
    template_name = "delivery/customer_update_form.html"

    def form_valid(self, form) -> str:
        valid_form = form.save(commit=False)
        valid_form.save()
        return redirect("delivery:customer-detail", self.object.pk)


class RegisterView(generic.CreateView):
    model = Customer
    form_class = RegisterForm
    template_name = "delivery/customer_register_form.html"

    def form_valid(self, form) -> HttpResponseRedirect:
        form.save()
        customer = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )
        login(self.request, customer)
        return HttpResponseRedirect(reverse("delivery:index"))


class PizzaMenuListView(LoginRequiredMixin, generic.ListView):
    model = Pizza
    pizza = Pizza.objects.select_related(
        "type_pizza_id"
    ).prefetch_related("topping")
    template_name = "delivery/pizza_menu.html"
    context_object_name = "pizza_menu"

    def get_context_data(self, **kwargs) -> dict:
        context = super(PizzaMenuListView, self).get_context_data(**kwargs)
        context["pizza_type"] = PizzaType.objects.all()
        return context

    def get_queryset(self) -> QuerySet:
        queryset = super().get_queryset()
        search_term = self.kwargs.get("type_id")
        if search_term is not None:
            queryset = queryset.filter(type_pizza=search_term)
        return queryset


class PizzaCreateView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    generic.CreateView
):
    permission_required = "delivery.add_pizza"
    model = Pizza
    fields = ["name", "type_pizza", "price", "ingredients"]
    success_url = reverse_lazy("delivery:pizza-menu-list")
    template_name = "delivery/pizza_update_create_form.html"


class PizzaUpdateView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    generic.UpdateView
):
    permission_required = "delivery.change_pizza"
    model = Pizza
    fields = ["name", "type_pizza", "price", "ingredients"]
    success_url = reverse_lazy("delivery:pizza-menu-list")
    template_name = "delivery/pizza_update_create_form.html"


class PizzaDeleteView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    generic.DeleteView
):
    permission_required = "delivery.delete_pizza"
    model = Pizza
    queryset = Pizza.objects.prefetch_related("order__pizza")
    success_url = reverse_lazy("delivery:pizza-menu-list")
    template_name = "delivery/pizza_delete_form.html"


class ToppingListView(LoginRequiredMixin, generic.ListView):
    model = Topping
    form_class = ToppingSearchForm
    queryset = Topping.objects.all()
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(ToppingListView, self).get_context_data(**kwargs)
        topping = self.request.GET.get("topping", "")
        context["topping_form"] = ToppingSearchForm(
            initial={"topping": topping}
        )
        return context

    def get_queryset(self) -> QuerySet:
        form = ToppingSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["topping"]
            )
        return self.queryset


class ToppingUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView
):
    permission_required = "delivery.change_topping"
    model = Topping
    fields = "__all__"
    success_url = reverse_lazy("delivery:topping-list")
    template_name = "delivery/topping_update_create_form.html"


class ToppingCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView
):
    permission_required = "delivery.add_topping"
    model = Topping
    fields = "__all__"
    success_url = reverse_lazy("delivery:topping-list")
    template_name = "delivery/topping_update_create_form.html"


class ToppingDeleteView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView
):
    permission_required = "delivery.delete_topping"
    model = Topping
    fields = "__all__"
    success_url = reverse_lazy("delivery:topping-list")
    template_name = "delivery/topping_delete_form.html"


class TotalPriceMixin:
    @abstractmethod
    def get_pizzas(self, order: Order) -> QuerySet:
        pass

    def get_total_price(self, orders: QuerySet) -> tuple:
        total_price = 0
        topping_total_price = 0
        for order in orders:
            for pizza in self.get_pizzas(order):
                total_price += pizza.price * pizza.quantity
                pizza.price_with_toppings = pizza.price * pizza.quantity
                pizza.save()
                if pizza.topping.all():
                    for topping in pizza.topping.all():
                        pizza.price_with_toppings += topping.price
                        topping_total_price += topping.price
                        total_price += topping_total_price
                        pizza.save()
        return total_price, topping_total_price


class OrderListView(TotalPriceMixin, LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = "delivery/order_list.html"
    context_object_name = "orders"

    def get_pizzas(self, order: Order) -> QuerySet:
        return order.pizza.all()

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(OrderListView, self).get_context_data(**kwargs)
        orders = self.get_queryset().prefetch_related("pizza__topping")
        total = self.get_total_price(orders)
        context["total_price"] = total[0]
        return context


class OrderAddPizzaView(LoginRequiredMixin, View):
    @staticmethod
    def post(request, pizza_id) -> str:
        pizza = Pizza.objects.get(id=pizza_id)
        customer = request.user
        order, _ = Order.objects.get_or_create(customer=customer)

        new_pizza = Pizza.objects.create(
            name=pizza.name,
            type_pizza=pizza.type_pizza,
            price=pizza.price,
            price_with_toppings=pizza.price_with_toppings,
            ingredients=pizza.ingredients,
            quantity=1,
            is_custom_pizza=True
        )

        order.pizza.add(new_pizza)

        return redirect("delivery:pizza-menu-list")


class OrderDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Order
    success_url = reverse_lazy("delivery:order-list")
    template_name = "delivery/order_list.html"

    def post(self, request, *args, **kwargs) -> str:
        pizza = Pizza.objects.get(id=kwargs.get("pizza_id"))
        order = Order.objects.get(id=kwargs.get("order_id"))
        order.pizza.remove(kwargs.get("pizza_id"))
        pizza.quantity = 1
        if pizza.topping.all():
            pizza.topping.clear()
        pizza.save()
        if order.pizza.count() == 0:
            order.delete()
        try:
            Pizza.objects.get(name=pizza.name)
        except Pizza.MultipleObjectsReturned:
            pizza.delete()
        return redirect("delivery:order-list")


class IncrementQuantityView(LoginRequiredMixin, View):
    @staticmethod
    def post(request, pk) -> str:
        pizza = Pizza.objects.get(id=pk)
        pizza.quantity += 1
        pizza.save()
        return redirect("delivery:order-list")


class DecrementQuantityView(LoginRequiredMixin, View):
    @staticmethod
    def post(request, pk) -> str:
        pizza = Pizza.objects.get(id=pk)
        if pizza.quantity > 1:
            pizza.quantity -= 1
            pizza.save()
        return redirect("delivery:order-list")


class FeedBackListView(generic.ListView):
    model = FeedBack
    queryset = FeedBack.objects.select_related(
        "customer"
    ).order_by("-created_time")
    template_name = "delivery/feedback.html"
    paginate_by = 3

    def post(self, request) -> str:
        form = FeedBackCreateForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.customer = self.request.user
            feedback.save()
        return redirect("delivery:feedback-list")


def create_receipt(request) -> str:
    order = Order.objects.filter(
        customer=request.user, status=False
    ).first()
    if order:
        Receipt.objects.create(customer_order=order)
        order.status = True
        order.save()
    return redirect("delivery:receipt-list")


class ReceiptListView(TotalPriceMixin, LoginRequiredMixin, generic.ListView):
    model = Receipt

templates/delivery/about_delivery.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <section id="about" class="about">
    <div class="container" data-aos="fade-up">
      <div class="section-header">
        <br>
        <h2>About Us</h2>
        <p><span>Together</span>, we create the best pizza ever (even better than the restaurant!)</p>
      </div>

      <div class="row gy-4">
         <div class="col-lg-7 position-relative about-img" style="background-image: url({% static 'assets/img/about_page.jpeg' %})" data-aos="fade-up" data-aos-delay="150">
         </div>
        <div class="col-lg-5 d-flex align-items-end" data-aos="fade-up" data-aos-delay="300">
          <div class="content ps-0 ps-lg-5">
            <p class="fst-italic">
             It’s all because we’re not afraid to get our hands dirty. We’re with you every step of the way, from shopping to the unboxing your Thepizzashop.ca products, to creating your culinary masterpieces and maintaining your precious equipment. Scout’s honor! ✌️
  Our mission?
            </p>
            <ul>
              <li><i class="bi bi-check2-all"></i> We’re not afraid to get our hands dirty… especially when it comes to making pizza!</li>
              <li><i class="bi bi-check2-all"></i> We can’t promise you the best price,
  but we can promise you the best service.</li>
              <li><i class="bi bi-check2-all"></i> We offer the best of the best all under one roof you can rest easy.</li>
              <li><i class="bi bi-check2-all"></i> We make a point of giving honest advice.</li>
              <li><i class="bi bi-check2-all"></i> We save you looooong delays
  and customs fees.</li>
            </ul>
            <p>
              It’s all because we’re not afraid to get our hands dirty. We’re with you every step of the way, from shopping to the unboxing your Thepizzashop.ca products, to creating your culinary masterpieces and maintaining your precious equipment. Scout’s honor! ✌️
  Our mission?
            </p>

            <div class="position-relative mt-4">
              <img src="{% static 'assets/img/about_page2.jpg' %}" class="img-fluid" alt="">
              <a href="https://www.youtube.com/watch?v=ADvf-PIZPLA" class="glightbox play-btn"></a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>
{% endblock %}

templates/delivery/bucket_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-10">

          <div class="d-flex justify-content-between align-items-center mb-4">
            <h3 class="fw-normal mb-0 text-black">Pizza Cart</h3>
          </div>
          <div class="card rounded-3 mb-4">
            <div class="card-body p-4">
              <div class="row d-flex justify-content-between align-items-center">
                <div class="col-md-2 col-lg-2 col-xl-2">
                  <img
                    src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img1.webp"
                    class="img-fluid rounded-3" alt="Cotton T-shirt">
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3">
                  <p class="lead fw-normal mb-2">Basic T-shirt</p>
                  <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                  <button class="btn btn-link px-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                  </button>

                  <input id="form1" min="0" name="quantity" value="2" type="number"
                    class="form-control form-control-sm" />

                  <button class="btn btn-link px-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                  </button>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                  <h5 class="mb-0">$499.00</h5>
                </div>
                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                  <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
              <button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/delivery/choose_toppings.html
{% extends "base.html"%}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
  <section class="vh-100">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-6 text-black">
          <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
            <div style="height: 70vh; width: 100vh; overflow: scroll;">
              <h1>Choose extra topping</h1>
              <form method="post" action="" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <div class="pt-1 mb-4">
                  <input class="btn btn-info btn-lg btn-block" type="submit" value="Submit">
                </div>
              </form>
            </div>

          </div>

        </div>
        <div class="col-sm-6 px-0 d-none d-sm-block">
          <img src="{% static 'assets/img/login.jpeg' %}"
            alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/delivery/feedback.html
{% extends "base.html" %}
{% load static %}

{% block content %}
   <section style="background-color: #eee;">
      <div class="container my-5 py-5" data-aos="fade-up">
        <div class="row d-flex justify-content-center">
          <div class="col-md-12 col-lg-10 col-xl-8">
            {% for feedback in feedback_list %}
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-start align-items-center">
                      <img class="rounded-circle shadow-1-strong me-3"
                        src="{% static 'assets/img/favicon2.png' %}" alt="avatar" width="60"
                        height="60" />
                      <div>
                        <h6 class="fw-bold text-primary mb-1">{{ feedback.customer.username }}</h6>
                        <p class="text-muted small mb-0">
                          {{ feedback.created_time }}
                        </p>
                      </div>
                    </div>

                    <p class="mt-3 mb-4 pb-2">
                      {{ feedback.comment }}
                    </p>

                  </div>
                </div>
                <br>
             {% endfor %}
              {% if user.is_authenticated %}
                <form action="{% url 'delivery:feedback-list' %}" method="post">
                  {% csrf_token %}
                  <div class="card-footer py-3 border-0">
                    <div class="d-flex flex-start w-100">
                      <img class="rounded-circle shadow-1-strong me-3"
                        src="{% static 'assets/img/favicon2.png' %}" alt="avatar" width="40"
                        height="40" />
                      <div class="form-outline w-100">
                        <input type="hidden" name="comment" id="input" class="shadow_input">
                        <textarea class="form-control" id="textAreaExample" rows="4"
                          style="background: #fff;" oninput = "document.querySelector('input#input').value = this.value;" placeholder="Leave feedback..."></textarea>
                        <label class="form-label" for="textAreaExample"></label>
                      </div>
                    </div>
                    <div class="float-end mt-2 pt-1">
                      <input type="submit" class="btn btn-primary btn-sm" value="Post comment">
                    </div>
                  </div>
                </form>
                {% else %}
                  <a href="{% url "login" %}"><h5>Login to write feedback</h5></a>
              {% endif %}
            </div>
          </div>
        </div>
      </section>
{% endblock %}

templates/delivery/ingredients_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
    <section id="topping" class="topping">
      <div class="container" data-aos="fade-up">
        <div class="section-header">
          <p>Choose <span>Extra Topping</span></p>
          <p>
            {% if perms.delivery.add_ingredients %}
              <a style="text-decoration: none; margin-left: 1000px" href="{% url 'delivery:pizza-create' %}">
                Add new topping
              </a>
            {% endif %}
          </p>
        </div>
        <form style="justify-content: right;" action="" method="get" class="form-inline">
          {{ ingredients_form|crispy }}
          <input type="submit" value="Search" class="btn btn-outline-primary" >
        </form>

        <br>
          <div class="row gy-5">
            {% for topping in ingredients_list %}
              <div class="col-lg-4 menu-item" style="text-align: center">
                <img src="{% static 'assets/img/ingredients/'|add:topping.name|add:'.jpeg' %}" class="menu-img img-fluid" alt="">
                <h4>
                  {{ topping.name }}
                  {% if perms.delivery.change_ingredients %}
                  <a style="text-decoration: none" href="{% url 'delivery:ingredients-update' pk=topping.id %}">🔄</a>
                  {% endif %}
                  {% if perms.delivery.add_ingredients %}
                  <a style="text-decoration: none" href="{% url 'delivery:ingredients-delete' pk=topping.id %}">
                    ❌
                  </a>
                  {% endif %}
                </h4>
                <p class="price">
                  {{ topping.price }}$
                </p>
              </div>
            {% endfor %}
          </div>
        </div>
    </section>
{% endblock %}

templates/delivery/receipt_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div id="invoice">
    <div class="invoice overflow-auto">
        <div style="min-width: 600px">
          {% for order in receipt_order %}
            <main>
                <div class="row contacts">
                    <div class="col invoice-to" style="margin-top: 60px">
                        <div class="text-gray-light">CUSTOMER:</div>
                        <h2 class="to">
                          {{ order.customer_order.customer.first_name }}
                          {{ order.customer_order.customer.last_name }}
                        </h2>
                        <div class="address">{{ order.customer_order.customer.address }}</div>
                        <div class="email"><a href="mailto:john@example.com">{{ order.customer_order.customer.email }}</a></div>
                        <div class="address">Order time: {{ order.order_time }}</div>
                        <div class="address">Order id: {{ order.id }}</div>
                    </div>
                </div>
                <table border="0" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th>Pizza id</th>
                            <th class="text-left">PIZZA</th>
                            <th class="text-right">PRICE</th>
                            <th class="text-right">Topping</th>
                            <th class="text-right">QUANTITY</th>
                            <th class="text-right">TOTAL</th>
                        </tr>
                    </thead>
                      {% for pizza in order.customer_order.pizza.all %}
                        <tbody>
                          <tr>
                              <td class="no">{{ pizza.id }}</td>
                              <td class="text-left"><h3>
                                {{ pizza.name }}
                              </h3>
                              </td>
                              <td class="unit">{{ pizza.price }} $</td>
                              {% if pizza.topping.all %}
                                <td class="qty">
                                  {% for topping in pizza.topping.all %}
                                    <h6>{{ topping.name }}: {{ topping.price }} $</h6>
                                  {% endfor %}
                                </td>
                              {% else %}
                                <td class="qty">-</td>
                              {% endif %}
                              <td class="unit">{{ pizza.quantity }}</td>
                              <td class="total">{{ pizza.price_with_toppings }} $</td>
                          </tr>
                        </tbody>
                      {% endfor %}
                    <tfoot>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="3">TOPPING TOTAL PRICE:</td>
                            <td>{{ topping_total_price }} $</td>
                        </tr>
                        <tr>
                            <td colspan="2"></td>
                            <td colspan="3">TOTAL PRICE:</td>
                            <td>{{ total_price }} $</td>
                        </tr>
                    </tfoot>
                </table>
                <div class="thanks" style="margin-top: 10px">
                  <a style="text-decoration: none" href="#myModal" class="trigger-btn btn btn-success" data-toggle="modal">Confirm Order</a>
                  <a class="btn btn-danger" style="margin-left: 1110px; text-decoration: none" href="{% url 'delivery:order-list' %}">Cancel</a>
                </div>
                <div class="text-left">
                  <!-- Button HTML (to Trigger Modal) -->
                </div>
                <!-- Modal HTML -->
                <div id="myModal" class="modal fade">
                  <div class="modal-dialog modal-confirm">
                    <div class="modal-content">
                      <div class="modal-header">
                        <div class="icon-box">
                          <i class="material-icons">&#xE876;</i>
                        </div>
                        <h4 class="modal-title w-100">Thank you for your order!</h4>
                      </div>
                      <div class="modal-body">
                        <p class="text-center">We have received your order and it is being processed. Our operator will contact you soon.</p>
                      </div>
                      <div class="modal-footer">
                        <a href="{% url 'delivery:clean-order' pk=order.customer_order.id %}" class="btn btn-success btn-block">OK</a>
                      </div>
                    </div>
                  </div>
                </div>
              </main>
          {% endfor %}
        </div>
        <div></div>
    </div>
</div>
{% endblock %}