delivery/urls.py
from django.urls import path

from delivery.views import (
    index,
    about,
    PizzaMenuListView,
    CustomerDetailView,
    CustomerUpdateView,
    ToppingListView,
    ToppingUpdateView,
    ToppingCreateView,
    ToppingDeleteView,
    RegisterView,
    PizzaUpdateView,
    PizzaCreateView,
    PizzaDeleteView,
    OrderListView,
    OrderAddPizzaView,
    OrderDeleteView,
    IncrementQuantityView,
    DecrementQuantityView,
    FeedBackListView,
    create_receipt,
    ReceiptListView,
    clean_order,
    ChooseToppingView,
)

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name="about"),
    path("menu/", PizzaMenuListView.as_view(), name="pizza-menu-list"),
    path(
        "menu/type/<int:type_id>/",
        PizzaMenuListView.as_view(),
        name="pizza-menu-type-list",
    ),
    path(
        "menu/pizza/<int:pk>/update/",
        PizzaUpdateView.as_view(),
        name="pizza-update"
    ),
    path(
        "menu/create/",
        PizzaCreateView.as_view(),
        name="pizza-create"
    ),
    path(
        "menu/<int:pk>/delete/",
        PizzaDeleteView.as_view(),
        name="pizza-delete"
    ),
    path(
        "customer/<int:pk>/",
        CustomerDetailView.as_view(),
        name="customer-detail"
    ),
    path(
        "customer/<int:pk>/update/",
        CustomerUpdateView.as_view(),
        name="customer-update",
    ),
    path(
        "registration/",
        RegisterView.as_view(),
        name="customer-register"
    ),
    path(
        "topping/<int:pk>/update",
        ToppingUpdateView.as_view(),
        name="topping-update"
    ),
    path(
        "topping/create/",
        ToppingCreateView.as_view(),
        name="topping-create"
    ),
    path(
        "topping/<int:pk>/delete/",
        ToppingDeleteView.as_view(),
        name="topping-delete"
    ),
    path(
        "topping/",
        ToppingListView.as_view(),
        name="topping-list"
    ),
    path(
        "order/",
        OrderListView.as_view(),
        name="order-list"
    ),
    path(
        "order/add-pizza/<int:pizza_id>/",
        OrderAddPizzaView.as_view(),
        name="order-add-pizza",
    ),

    path(
        "order-delete/<int:order_id>/<int:pizza_id>/",
        OrderDeleteView.as_view(),
        name="order-delete",
    ),
    path(
        "increment/<int:pk>/",
        IncrementQuantityView.as_view(),
        name="order-increment"
    ),
    path(
        "decrement/<int:pk>/",
        DecrementQuantityView.as_view(),
        name="order-decrement"
    ),
    path("feedback/", FeedBackListView.as_view(), name="feedback-list"),
    path("create-receipt/", create_receipt, name="receipt-create"),
    path("receipt/", ReceiptListView.as_view(), name="receipt-list"),
    path("clean-order/<int:pk>/", clean_order, name="clean-order"),
    path(
        "order/<int:pk>/add_toppings/",
        ChooseToppingView.as_view(),
        name="choose-topping"
    ),
]

app_name = "delivery"

delivery_pizza/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("delivery.urls", namespace="delivery")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
{% load static %}

<!-- ======= Footer ======= -->
{% block footer %}
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022 - US<br>
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Contact us</h4>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> SecurePizza@gmail.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 11AM</strong> - 23PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright text-center">
        &copy; Copyright <strong><span>SecurePizza</span></strong>. <br>All Rights Reserved
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->
{% endblock %}

templates/includes/header.html
{% load static %}

{% block header %}
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a  style="text-decoration: none" href="/" class="logo d-flex align-items-center me-auto me-lg-0">
        <img src="{% static 'assets/img/favicon2.png' %}" alt="">
        <h1>Secure Pizza<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'delivery:index' %}">Home</a></li>
          <li><a href="{% url 'delivery:about' %}">About</a></li>
          <li><a href="{% url 'delivery:pizza-menu-list' %}">Menu</a></li>
          <li><a href="{% url 'delivery:topping-list' %}">Topping</a></li>
          <li><a href="{% url 'delivery:feedback-list' %}">Feedback</a></li>
          <li><a href="{% url 'delivery:order-list' %}">
            <img src="{% static 'assets/img/Cart.png' %}" width="25" height="25">
          </a>
          </li>
        </ul>

      </nav>
      {% if not user.is_authenticated %}
        <div>
          <a style="text-decoration: none" class="btn-book-a-table" href="{% url 'delivery:customer-register' %}">Register</a>
          <a style="text-decoration: none" class="btn-book-a-table" href="{% url 'login' %}">Login</a>
        </div>
        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      {% else %}
        <div>
          <a style="text-decoration: none" class="btn-book-a-table" href="{{ user.get_absolute_url }}">Welcome, {{ user.username }}</a>
          <a style="text-decoration: none" class="btn-book-a-table" href="{% url 'logout' %}">Logout</a>
        </div>
        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      {% endif %}

    </div>
  </header>
{% endblock %}

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>

{% endif %}